### ISSUE TITLE
Double Jumping immediately after jumping causes the character to flip (???) a bit after the animation starts

### ISSUE THREAD

**Issue by DiamondBor** [00826/motion-rbx#1]
I'm not sure if that's the right way to put it, but it's very simple to reproduce; keep repeatedly double jumping _before_ your character reaches the freefalling state (while their state is still jumping).

Here's a video showing the issue; the first double jump is the expected result, and the second double jump is what happens if you double jump while you're in the Jumping state.
https://github.com/user-attachments/assets/f024bdad-cd28-4efd-9066-761b0afefd5f

**Comment by 00826** [comment]
the double-jump aux state can be activated on the condition that `Humanoid.FloorMaterial == Enum.Material.Air`
if preferred, you could add special conditions in the init.lua file, such as distance from the floor or time elapsed since the humanoid entered the .Jumping or .Freefall state
